model_name: ganomaly

seed: 42

split_dir: ./data/splits

# target_size: !<tag:yaml.org,2002:seq> [128,128]
# target_size: !<tag:yaml.org,2002:seq> [32,32]
target_size: !<tag:yaml.org,2002:seq> [128,128]
batch_size: 32
latent_vec_size: 256
n_features: 100
lr: 0.0001
num_epochs: 120
extra_layers: 3
wadv: 2
wcon: 50
wenc: 1
kernel_size: 4 # other values break it lol