model_name: ganomaly

seed: 42

split_dir: ./data/splits

# target_size: !<tag:yaml.org,2002:seq> [128,128]
# target_size: !<tag:yaml.org,2002:seq> [32,32]
target_size: !<tag:yaml.org,2002:seq> [128,128]
batch_size: 100
latent_vec_size: 256
n_features: 40
lr: 0.0001
num_epochs: 100
extra_layers: 5
wadv: 1
wcon: 50
wenc: 1
kernel_size: 2 # other values break it lol