model_name: ganomaly

seed: 42

split_dir: ./data/splits

target_size: !<tag:yaml.org,2002:seq> [128,128]
# target_size: !<tag:yaml.org,2002:seq> [64,64]
batch_size: 32
latent_vec_size : 100
lr: 0.001
num_epochs: 50