model_name: ganomaly

seed: 42

split_dir: ./data/splits

# target_size: !<tag:yaml.org,2002:seq> [128,128]
# target_size: !<tag:yaml.org,2002:seq> [32,32]
target_size: !<tag:yaml.org,2002:seq> [128,128]
batch_size: 128
latent_vec_size: 128
n_features: 64
lr: 0.0001
num_epochs: 120
extra_layers: 2
wadv: 3
wcon: 100
wenc: 1
kernel_size: 4 # other values break it lol