model_name: ganomaly

seed: 42

split_dir: ./data/splits

target_size: !<tag:yaml.org,2002:seq> [128,128]
# target_size: !<tag:yaml.org,2002:seq> [64,64]
batch_size: 128
latent_vec_size : 1248
n_features: 64
lr: 0.002
num_epochs: 100
extra_layers: 2